# Requête GET pour récupérer tous les utilisateurs
GET http://localhost:8081/users

###

POST http://localhost:8081/users
Content-Type: application/json

{
  "name": "Alice Admin",
  "email": "alice.admin@example.com",
  "role": "ADMIN"
}


###

# Requête GET pour récupérer tous les utilisateurs
DELETE  http://localhost:8081/users/1

###

POST http://localhost:8081/users
Content-Type: application/json

{
  "name": "Paul Volontaire",
  "email": "pauln@example.com",
  "role": "VOLONTAIRE"
}

###

POST http://localhost:8081/users
Content-Type: application/json

{
  "name": "Cyril user",
  "email": "cyril.admin@example.com",
  "role": "USER"
}
