server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: room-service
          uri: http://localhost:8083
          predicates:
            - Path=/rooms/**
        - id: window-service
          uri: http://localhost:8082
          predicates:
            - Path=/windows/**
        - id: sensor-service
          uri: http://localhost:8081
          predicates:
            - Path=/sensors/**
