name: Build and deploy JAR app to Azure Web App - orchestratorMS

on:
  push:
    branches:
      - REST_Service
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven in orchestratorMS folder
        run: mvn clean compile -f Projet_archi_service/user-service/pom.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Projet_archi_service/user-service/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
     
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C04D5181F90466AB40A0E5B6C87BC2B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D51546960274F36B33379C43BCDDBBE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48F592B9BD454FCCA7156A05D7D2DF48 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Projet_archi_service/user-service'
          slot-name: 'Production'
          package: '*.jar'
         
